# Generated by Django 5.0.6 on 2024-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='time',
        ),
        migrations.AddField(
            model_name='medicine',
            name='times',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='days',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.IntegerField(),
        ),
    ]
