# Generated by Django 5.0.6 on 2024-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0002_remove_medicine_time_medicine_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='times',
            field=models.TimeField(),
        ),
    ]
