# Generated by Django 5.0.6 on 2024-06-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pills', '0005_reminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
